global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'synaptica'
    scheme: 'https'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'synaptica-production.up.railway.app'
